### ISSUE TITLE
Add item: Unexpected token  < 

### ISSUE THREAD

**Issue by mstylinaou28** [Bruno17/MIGX#319]
When i press 'Done' to save an item i get his error:

(<br />
<b>Fatal error</b>:  Uncaught Error: Call to a member function get() on null in MYPATH\core\components\migx\processors\mgr\default\update.php:286
Stack trace:
#0 MYPATH\core\components\migx\processors\mgr\migxdb\update.php(18): include_once()
#1 MYPATH\core\model\modx\modprocessor.class.php(354): include('C:\\XAMPP\\htdocs...')
#2 MYPATH\core\model\modx\modprocessor.class.php(173): modDeprecatedProcessor-&gt;process()
#3 MYPATH\core\model\modx\modx.class.php(1705): modProcessor-&gt;run()
#4 MYPATH\core\model\modx\modconnectorresponse.class.php(140): modX-&gt;runProcessor('mgr/migxdb/upda...', Array, Array)
#5 MYPATH\core\model\modx\modconnectorrequest.class.php(82): modConnectorResponse-&gt;outputContent(Array)
#6 MYPATH\core\model\modx\modconnectorrequest.class.php(69): modConnectorRequest-&gt;prepareResponse(Array)
#7 MYPATH\assets\components\migx\connector in <b>MYPATH\core\components\migx\processors\mgr\default\update.php</b> on line <b>286</b><br />
)

Console: 
VM5018:1 Uncaught SyntaxError: Unexpected token <
    at doDecode (ext-all.js:21)
    at Object.decode (ext-all.js:21)
    at MODx.Ajax.success (modx.js?v=ef8c0aed:518)
    at Ext.data.Connection.handleResponse (ext-all.js:21)
    at f (ext-base.js:21)
    at m (ext-base.js:21)
    at ext-base.js:21

**Comment by mstylinaou28** [comment]
Found it. My class name didn't match my schema
