### ISSUE TITLE
error phpthumbon

### ISSUE THREAD

**Issue by rasxod** [Bruno17/MIGX#410]
modx3.0.3

when using
`{$_modx->user.photo | phpthumbon : 'w=200&h=200&zc=1'}`

```
[22-Apr-2023 11:46:54 Europe/Moscow] PHP Fatal error:  Uncaught Error: Call to a member function make() on null in D:\www\****\core\components\phpthumbon\model\phpthumbon\phpthumbon.class.php:653
Stack trace:
#0 D:\www\****\core\components\phpthumbon\model\phpthumbon\phpthumbon.class.php(337): phpThumbOn->makeDir()
#1 D:\www\****\core\components\phpthumbon\model\phpthumbon\phpthumbon.class.php(300): phpThumbOn->makeCacheDir()
#2 D:\www\****\core\cache\includes\elements\modx\revolution\modsnippet\19.include.cache.php(24): phpThumbOn->run()
#3 D:\www\****\core\src\Revolution\modScript.php(88): include('D:\\www\\****\\co...')
#4 D:\www\****\core\components\pdotools\src\CoreTools.php(358): MODX\Revolution\modScript->process()
#5 D:\www\****\core\components\pdotools\src\Parsing\Fenom\Fenom.php(686): ModxPro\PdoTools\CoreTools->runSnippet()
#6 D:\www\****\core\components\pdotools\vendor\fenom\fenom\src\Fenom\Template.php(487) : eval()'d code(70): ModxPro\PdoTools\Parsing\Fenom\Fenom->ModxPro\PdoTools\Parsing\Fenom\{closure}()
#7 D:\www\****\core\components\pd in D:\www\****\core\components\phpthumbon\model\phpthumbon\phpthumbon.class.php on line 653
```

MODX Log
```
[2023-04-22 11:46:54] (ERROR @ D:\www\****\core\vendor\xpdo\xpdo\src\xPDO\xPDO.php : 666) Could not load class: modFileHandler from modfilehandler
[2023-04-22 11:46:54] (ERROR @ D:\www\****\core\vendor\xpdo\xpdo\src\xPDO\xPDO.php : 1272) Problem getting service fileHandler, instance of class modFileHandler, from path 
```

**Comment by rasxod** [comment]
it turned out that this is an extension and does not yet support MODX3
